package main;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author lover
 */
public class EliminarTrans extends javax.swing.JFrame {

    /**
     * Creates new form EliminarTrans
     */
    public EliminarTrans() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        barraPanel = new javax.swing.JPanel();
        barraText = new javax.swing.JLabel();
        atrasPanel = new javax.swing.JPanel();
        atrasText = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        transToDelete = new javax.swing.JTextField();
        Text1 = new javax.swing.JLabel();
        insertPanel = new javax.swing.JPanel();
        insertText = new javax.swing.JLabel();
        ErrorF = new javax.swing.JTextField();
        confirmRegistroText = new javax.swing.JLabel();
        confirmRegistroIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        fondoPanel.setBackground(new java.awt.Color(242, 240, 241));
        fondoPanel.setMinimumSize(new java.awt.Dimension(860, 600));
        fondoPanel.setPreferredSize(new java.awt.Dimension(854, 600));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraPanel.setBackground(new java.awt.Color(97, 109, 167));
        barraPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraPanelMouseDragged(evt);
            }
        });
        barraPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraPanelMousePressed(evt);
            }
        });
        barraPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraText.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        barraText.setForeground(new java.awt.Color(255, 255, 255));
        barraText.setText("ELIMINAR TRANSACCIÓN");
        barraPanel.add(barraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        fondoPanel.add(barraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 140));

        atrasPanel.setBackground(new java.awt.Color(253, 253, 253));
        atrasPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                atrasPanelMousePressed(evt);
            }
        });

        atrasText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atrasText.setForeground(new java.awt.Color(97, 109, 167));
        atrasText.setText("Atrás");

        javax.swing.GroupLayout atrasPanelLayout = new javax.swing.GroupLayout(atrasPanel);
        atrasPanel.setLayout(atrasPanelLayout);
        atrasPanelLayout.setHorizontalGroup(
            atrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atrasPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(atrasText)
                .addGap(51, 51, 51))
        );
        atrasPanelLayout.setVerticalGroup(
            atrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atrasPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(atrasText)
                .addGap(12, 12, 12))
        );

        fondoPanel.add(atrasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 140, 40));
        fondoPanel.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 348, -1));

        transToDelete.setBackground(new java.awt.Color(242, 240, 241));
        transToDelete.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        transToDelete.setForeground(new java.awt.Color(98, 106, 163));
        transToDelete.setBorder(null);
        transToDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transToDeleteMouseClicked(evt);
            }
        });
        transToDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transToDeleteActionPerformed(evt);
            }
        });
        transToDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                transToDeleteKeyTyped(evt);
            }
        });
        fondoPanel.add(transToDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 334, 25));

        Text1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Text1.setForeground(new java.awt.Color(96, 107, 167));
        Text1.setText("Cédula de transacción a eliminar:");
        fondoPanel.add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 290, 30));

        insertPanel.setBackground(new java.awt.Color(253, 253, 253));
        insertPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                insertPanelMousePressed(evt);
            }
        });

        insertText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insertText.setForeground(new java.awt.Color(97, 109, 167));
        insertText.setText("Ingresar");

        javax.swing.GroupLayout insertPanelLayout = new javax.swing.GroupLayout(insertPanel);
        insertPanel.setLayout(insertPanelLayout);
        insertPanelLayout.setHorizontalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(insertText)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        insertPanelLayout.setVerticalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondoPanel.add(insertPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        ErrorF.setEditable(false);
        ErrorF.setBackground(new java.awt.Color(242, 240, 241));
        ErrorF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ErrorF.setForeground(new java.awt.Color(255, 102, 102));
        ErrorF.setBorder(null);
        ErrorF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ErrorFMouseClicked(evt);
            }
        });
        ErrorF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorFActionPerformed(evt);
            }
        });
        ErrorF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ErrorFKeyTyped(evt);
            }
        });
        fondoPanel.add(ErrorF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 320, 25));

        confirmRegistroText.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        confirmRegistroText.setForeground(new java.awt.Color(96, 107, 167));
        confirmRegistroText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoPanel.add(confirmRegistroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 340, 30));
        fondoPanel.add(confirmRegistroIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void barraPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_barraPanelMouseDragged

    private void barraPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_barraPanelMousePressed

    private void atrasPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasPanelMouseEntered
        // TODO add your handling code here:
        setColor(atrasPanel);
    }//GEN-LAST:event_atrasPanelMouseEntered

    private void atrasPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasPanelMouseExited
        // TODO add your handling code here:
        resetColor(atrasPanel);
    }//GEN-LAST:event_atrasPanelMouseExited


    private void atrasPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasPanelMousePressed
        // TODO add your handling code here:
        new Home().show();
        this.hide();
    }//GEN-LAST:event_atrasPanelMousePressed

    private void transToDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transToDeleteMouseClicked
        transToDelete.setText("");
    }//GEN-LAST:event_transToDeleteMouseClicked

    private void transToDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transToDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transToDeleteActionPerformed

    private void transToDeleteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transToDeleteKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (transToDelete.getText().trim().length() == 4) {
            evt.consume();
        }
    }//GEN-LAST:event_transToDeleteKeyTyped

    private void insertPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertPanelMouseEntered
        // TODO add your handling code here:
        setColor(insertPanel);
    }//GEN-LAST:event_insertPanelMouseEntered

    private void insertPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertPanelMouseExited
        resetColor(insertPanel);
    }//GEN-LAST:event_insertPanelMouseExited

    private void insertPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertPanelMousePressed
        if (transToDelete.getText().isEmpty()) {
            ErrorF.setText("Digite todos los campos");
            confirmRegistroText.setForeground(new java.awt.Color(159, 101, 100));
            confirmRegistroText.setText("La transacción no se ha eliminado");
            confirmRegistroIcon.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wrong.png")).getImage().getScaledInstance(240, 240, Image.SCALE_SMOOTH)));
        } else {
            ErrorF.setText("");
            String idTFieldToDelete = transToDelete.getText();
            String fileTName = "Transacciones";
            String fileTNameNew = fileTName + "New";
            File archiveTName = new File(fileTName + ".txt");
            File archiveTNameNew = new File(fileTNameNew + ".txt");
            PrintWriter lineWriter;
            try {
                if (!archiveTName.exists()) {
                    archiveTName.createNewFile();
                }

                // Cedula
                if (idTFieldToDelete.length() < 1) {
                    transToDelete.setText("Cédula incorrecta");
                    ErrorF.setText("Digite la cédula correctamente");
                }
                // Verifica si está
                if (Leer(fileTName, idTFieldToDelete)) {
                    confirmRegistroText.setForeground(new java.awt.Color(96, 107, 167));
                    confirmRegistroText.setText("La transacción se ha eliminado correctamente");
                    confirmRegistroIcon.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png")).getImage().getScaledInstance(240, 240, Image.SCALE_SMOOTH)));
                    rehacer(fileTName, idTFieldToDelete, fileTNameNew);
                    archiveTName.delete();
                    lineWriter = null;
                    File NewFile = new File("Transacciones.txt");
                    lineWriter = new PrintWriter(NewFile);
                    try {
                        BufferedReader bro = new BufferedReader(new FileReader(fileTNameNew + ".txt"));
                        String line = null; //definición de line
                        while ((line = bro.readLine()) != null) {
                            String temp[] = line.split(":");
                            lineWriter.println(temp[0] + ":" + temp[1] + ":" + temp[2]);
                        }
                        bro.close();
                        lineWriter.close();
                        archiveTNameNew.delete();
                    } catch (IOException ex) {
                        System.out.println("No se encontro archivo");
                    }
                } else {
                    ErrorF.setText("La cédula no está registrada");
                    confirmRegistroText.setForeground(new java.awt.Color(159, 101, 100));
                    confirmRegistroText.setText("La transacción no se ha eliminado");
                    confirmRegistroIcon.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wrong.png")).getImage().getScaledInstance(240, 240, Image.SCALE_SMOOTH)));
                }
            } catch (IOException ex) {
                ErrorF.setText("Error creando el archivo");
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_insertPanelMousePressed

    private void ErrorFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorFMouseClicked

    }//GEN-LAST:event_ErrorFMouseClicked

    private void ErrorFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorFActionPerformed

    private void ErrorFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ErrorFKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (ErrorF.getText().trim().length() == 4) {
            evt.consume();
        }
    }//GEN-LAST:event_ErrorFKeyTyped

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(204, 204, 204));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(253, 253, 253));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarTrans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ErrorF;
    private javax.swing.JLabel Text1;
    private javax.swing.JPanel atrasPanel;
    private javax.swing.JLabel atrasText;
    private javax.swing.JPanel barraPanel;
    private javax.swing.JLabel barraText;
    private javax.swing.JLabel confirmRegistroIcon;
    private javax.swing.JLabel confirmRegistroText;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JPanel insertPanel;
    private javax.swing.JLabel insertText;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextField transToDelete;
    // End of variables declaration//GEN-END:variables

    // Recorre el archivo
    public static boolean Leer(String fileName, String id) {
        boolean hay = false;
        while (hay == false) {
            try {
                BufferedReader br = new BufferedReader(new FileReader(fileName + ".txt"));
                String line = null; //definición de line
                while ((line = br.readLine()) != null) {
                    String temp[] = line.split(":");
                    if (id.equals(temp[0])) {
                        return true;
                    }
                }
                br.close();
                hay = true;
            } catch (IOException ex) {
                System.out.println("No se encontro archivo");
                hay = false;
            }
        }
        return false;
    }

    public static void rehacer(String fileTName, String id, String fileTNameNew) {
        boolean hay = false;
        // nuevo archivo
        FileWriter fileWriter = null;
        PrintWriter lineWriter = null;
        File archiveNameNew = new File(fileTNameNew + ".txt");

        try {
            if (!archiveNameNew.exists()) {
                archiveNameNew.createNewFile();
            }
            fileWriter = new FileWriter(archiveNameNew, true);
            lineWriter = new PrintWriter(fileWriter);
        } catch (IOException ex) {
            //ErrorD.setText("Error creando el archivo");
            ex.printStackTrace();
        }

        boolean isTrans = false;
        while (hay == false) {
            try {
                BufferedReader br2 = new BufferedReader(new FileReader(fileTName + ".txt"));
                String line = null; //definición de line
                while ((line = br2.readLine()) != null) {
                    String temp[] = line.split(":");
                    System.out.println("isTrans " + isTrans);
                    if (id.equals(temp[0]) && isTrans == false) {
                        isTrans = true;
                    } else if (!id.equals(temp[0])) {
                        lineWriter.println(temp[0] + ":" + temp[1] + ":" + temp[2]);
                    }
                }
                br2.close();
                hay = true;
                lineWriter.close();
                fileWriter.close();
            } catch (IOException ex) {
                System.out.println("No se encontro archivo");
                hay = false;
            }
        }
    }
}
