
package main;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JPanel;


/**
 *
 * @author lover
 */
public class Saldo extends javax.swing.JFrame {

    int control = 0;
    String Clientes = "Clientes";
    String Transacciones = "Transacciones";

    void mostrarArchivo(String file_name) {
        try {
            BufferedReader buffer = new BufferedReader(new FileReader(file_name + ".txt"));
            String line = null; //definición de line
            archivoTextArea.setText(null);
            while ((line = buffer.readLine()) != null) {
                String campos[] = line.split(":");
                archivoTextArea.append(campos[0] + "\t\t" + campos[1] + "\t            " + campos[2] + "\n");
            }
            buffer.close();

        } catch (IOException ex) {
            archivoTextArea.setText("No se encontró archivo");
        }
    }
    
    public Saldo() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarArchivo(Clientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        barraPanel = new javax.swing.JPanel();
        barraText = new javax.swing.JLabel();
        atrasPanel = new javax.swing.JPanel();
        atrasLabel = new javax.swing.JLabel();
        textAreaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        archivoTextArea = new javax.swing.JTextArea();
        campo1Label = new javax.swing.JLabel();
        campo2Label = new javax.swing.JLabel();
        campo3Label = new javax.swing.JLabel();
        clientesPanel = new javax.swing.JPanel();
        clientesLabel = new javax.swing.JLabel();
        transPanel = new javax.swing.JPanel();
        transLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        fondoPanel.setBackground(new java.awt.Color(242, 240, 241));
        fondoPanel.setMinimumSize(new java.awt.Dimension(860, 600));
        fondoPanel.setPreferredSize(new java.awt.Dimension(854, 600));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraPanel.setBackground(new java.awt.Color(97, 109, 167));
        barraPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraPanelMouseDragged(evt);
            }
        });
        barraPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraPanelMousePressed(evt);
            }
        });
        barraPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraText.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        barraText.setForeground(new java.awt.Color(255, 255, 255));
        barraText.setText("SALDO");
        barraPanel.add(barraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        fondoPanel.add(barraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 140));

        atrasPanel.setBackground(new java.awt.Color(253, 253, 253));
        atrasPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                atrasPanelMousePressed(evt);
            }
        });

        atrasLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atrasLabel.setForeground(new java.awt.Color(97, 109, 167));
        atrasLabel.setText("Atrás");

        javax.swing.GroupLayout atrasPanelLayout = new javax.swing.GroupLayout(atrasPanel);
        atrasPanel.setLayout(atrasPanelLayout);
        atrasPanelLayout.setHorizontalGroup(
            atrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atrasPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(atrasLabel)
                .addGap(51, 51, 51))
        );
        atrasPanelLayout.setVerticalGroup(
            atrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atrasPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(atrasLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        fondoPanel.add(atrasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 140, 40));

        jScrollPane1.setBorder(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        archivoTextArea.setEditable(false);
        archivoTextArea.setColumns(20);
        archivoTextArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        archivoTextArea.setRows(5);
        jScrollPane1.setViewportView(archivoTextArea);

        javax.swing.GroupLayout textAreaPanelLayout = new javax.swing.GroupLayout(textAreaPanel);
        textAreaPanel.setLayout(textAreaPanelLayout);
        textAreaPanelLayout.setHorizontalGroup(
            textAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        textAreaPanelLayout.setVerticalGroup(
            textAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondoPanel.add(textAreaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 660, 410));

        campo1Label.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        campo1Label.setForeground(new java.awt.Color(0, 0, 0));
        campo1Label.setText("Nombre");
        fondoPanel.add(campo1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        campo2Label.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        campo2Label.setForeground(new java.awt.Color(0, 0, 0));
        campo2Label.setText("Cédula");
        fondoPanel.add(campo2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        campo3Label.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        campo3Label.setForeground(new java.awt.Color(0, 0, 0));
        campo3Label.setText("Saldo");
        fondoPanel.add(campo3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        clientesPanel.setBackground(new java.awt.Color(204, 204, 204));
        clientesPanel.setForeground(new java.awt.Color(204, 204, 204));
        clientesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientesPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientesPanelMousePressed(evt);
            }
        });

        clientesLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        clientesLabel.setForeground(new java.awt.Color(97, 109, 167));
        clientesLabel.setText("Clientes");

        javax.swing.GroupLayout clientesPanelLayout = new javax.swing.GroupLayout(clientesPanel);
        clientesPanel.setLayout(clientesPanelLayout);
        clientesPanelLayout.setHorizontalGroup(
            clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(clientesLabel)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        clientesPanelLayout.setVerticalGroup(
            clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientesLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondoPanel.add(clientesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 130, 30));

        transPanel.setBackground(new java.awt.Color(255, 255, 255));
        transPanel.setForeground(new java.awt.Color(255, 255, 255));
        transPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transPanelMousePressed(evt);
            }
        });

        transLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        transLabel.setForeground(new java.awt.Color(97, 109, 167));
        transLabel.setText("Transacciones");

        javax.swing.GroupLayout transPanelLayout = new javax.swing.GroupLayout(transPanel);
        transPanel.setLayout(transPanelLayout);
        transPanelLayout.setHorizontalGroup(
            transPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(transLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        transPanelLayout.setVerticalGroup(
            transPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondoPanel.add(transPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void barraPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_barraPanelMouseDragged

    private void barraPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_barraPanelMousePressed

    private void atrasPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasPanelMouseEntered
        // TODO add your handling code here:
        setColor(atrasPanel);
    }//GEN-LAST:event_atrasPanelMouseEntered

    private void atrasPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasPanelMouseExited
        // TODO add your handling code here:
        resetColor(atrasPanel);
    }//GEN-LAST:event_atrasPanelMouseExited

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(204, 204, 204));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(253, 253, 253));
    }

    private void atrasPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasPanelMousePressed
        // TODO add your handling code here:
        new Home().show();
        this.hide();
    }//GEN-LAST:event_atrasPanelMousePressed

    private void clientesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesPanelMouseEntered
        setColor(clientesPanel);
    }//GEN-LAST:event_clientesPanelMouseEntered

    private void clientesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesPanelMouseExited
        if (control != 0) {
            resetColor(clientesPanel);
        }
    }//GEN-LAST:event_clientesPanelMouseExited

    private void clientesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesPanelMousePressed
        mostrarArchivo(Clientes);
        control = 0;
        campo1Label.setText("Nombre");
        campo2Label.setText("Cédula");
        campo3Label.setText("Saldo");
        setColor(clientesPanel);
        resetColor(transPanel);
    }//GEN-LAST:event_clientesPanelMousePressed

    private void transPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transPanelMouseEntered
        setColor(transPanel);
    }//GEN-LAST:event_transPanelMouseEntered

    private void transPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transPanelMouseExited
        if (control != 1) {
            resetColor(transPanel);
        }
    }//GEN-LAST:event_transPanelMouseExited

    private void transPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transPanelMousePressed
        mostrarArchivo(Transacciones);
        control = 1;
        campo1Label.setText("Cédula");
        campo2Label.setText("Tipo");
        campo3Label.setText("Valor");
        setColor(transPanel);
        resetColor(clientesPanel);
    }//GEN-LAST:event_transPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea archivoTextArea;
    private javax.swing.JLabel atrasLabel;
    private javax.swing.JPanel atrasPanel;
    private javax.swing.JPanel barraPanel;
    private javax.swing.JLabel barraText;
    private javax.swing.JLabel campo1Label;
    private javax.swing.JLabel campo2Label;
    private javax.swing.JLabel campo3Label;
    private javax.swing.JLabel clientesLabel;
    private javax.swing.JPanel clientesPanel;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel textAreaPanel;
    private javax.swing.JLabel transLabel;
    private javax.swing.JPanel transPanel;
    // End of variables declaration//GEN-END:variables
}
